import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container top-110   d-flex mx-auto "
       >
          <div>
            <div className="card border-light mb-3" style={{
              maxWidth: '50rem',
            }}>
              <div className="card-header">First Blog Post <i className="bi bi-box-arrow-up-right"></i>
                <div className="float-end">
                  <i className=" icon bi bi-facebook"></i>
                  <i className=" icon bi bi-share-fill"></i>
                  <i className=" icon bi bi-bookmark-plus-fill"></i>
                  {/* <i class="bi bi-bookmark-check-fill"></i> */}
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">
                  Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
                </p>

              </div>

            </div>
            <div className="card border-light mb-3" style={{
              maxWidth: '50rem',
            }}>
              <div className="card-header">First Blog Post <i className="bi bi-box-arrow-up-right"></i>
                <div className="float-end">
                  <i className=" icon bi bi-facebook"></i>
                  <i className=" icon bi bi-share-fill"></i>
                  <i className=" icon bi bi-bookmark-plus-fill"></i>
                  {/* <i class="bi bi-bookmark-check-fill"></i> */}
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">
                  Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
                </p>

              </div>

            </div>
            <div className="card border-light mb-3" style={{
              maxWidth: '50rem',
            }}>
              <div className="card-header">First Blog Post <i className="bi bi-box-arrow-up-right"></i>
                <div className="float-end">
                  <i className=" icon bi bi-facebook"></i>
                  <i className=" icon bi bi-share-fill"></i>
                  <i className=" icon bi bi-bookmark-plus-fill"></i>
                  {/* <i class="bi bi-bookmark-check-fill"></i> */}
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">
                  Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
                </p>

              </div>

            </div>
          </div>
          <div>
            <div className="card border-primary mb-3" style={{
              maxWidth: '20rem',
              marginLeft: '2rem',
            }}>
              <div className="card-header"><i className=" icon bi bi-person-circle"></i> Jhon Doe</div>
              <div className="card-body">
                <h4 className="card-title"> Hello, Author here. </h4>
                <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
          </div>
          </div>
      </main>
    </>
  )
}
