import Head from 'next/head'
import { useEffect } from 'react'
import { UserContext } from '@/context/userContext'
import { useContext } from 'react'
import Link from 'next/link'


export default function Home() {
  const { user, setUser } = useContext(UserContext)
  useEffect(() => {
    fetch('/api/user')
      .then((res) => res.json())
      .then((data) => {
        console.log('user :', data)
        setUser(data)
      })

  }, [])
  return (
    <>
      <Head>
        <title> Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>


        <div className="container top-110 flex-sm-column flex-md-row flex-lg-row   d-flex mx-auto "

        >


          <div className=" "
          style={{
            marginRight: '3rem',
          }}
          >
            <div className="card border-light mb-3" style={{
              maxWidth: '50rem',
            }}>
              <div className='d-flex justify-content-between mb-4'>
                <ol className="breadcrumb">

                  <li className="breadcrumb-item active">
                    Home | 🖊️ <span className="text-capitalize">{user.name ? user.name : "Unregistered"}</span>
                  </li>

                </ol>
                <button className="btn btn-primary rounded "

                >
                  {
                    user.name ? (
                      <Link className="nav-link" href="addpost">
                        Create New Post
                      </Link>
                    ) : (
                      <Link className="nav-link" href="login">
                        Login to Create Post
                      </Link>
                    )
                  }
                </button>
              </div>


              <div className="card-header text-primary fw-bold">First Blog Post <i className="bi bi-box-arrow-up-right"></i>
                <div className="float-end">
                  <i className=" icon bi bi-facebook"></i>
                  <i className=" icon bi bi-share-fill"></i>
                  <i className=" icon bi bi-bookmark-plus-fill"></i>
                  {/* <i class="bi bi-bookmark-check-fill"></i> */}
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">
                  Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
                </p>

              </div>

            </div>
            <div className="card border-light mb-3" style={{
              maxWidth: '50rem',
            }}>
              <div className="card-header  text-primary fw-bold">First Blog Post <i className="bi bi-box-arrow-up-right"></i>
                <div className="float-end">
                  <i className=" icon bi bi-facebook"></i>
                  <i className=" icon bi bi-share-fill"></i>
                  <i className=" icon bi bi-bookmark-plus-fill"></i>
                  {/* <i class="bi bi-bookmark-check-fill"></i> */}
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">
                  Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
                </p>

              </div>

            </div>
            <div className="card border-light mb-3" style={{
              maxWidth: '50rem',
            }}>
              <div className="card-header  text-primary fw-bold">First Blog Post <i className="bi bi-box-arrow-up-right"></i>
                <div className="float-end">
                  <i className=" icon bi bi-facebook"></i>
                  <i className=" icon bi bi-share-fill"></i>
                  <i className=" icon bi bi-bookmark-plus-fill"></i>
                  {/* <i class="bi bi-bookmark-check-fill"></i> */}
                </div>
              </div>
              <div className="card-body">
                <p className="card-text">
                  Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
                </p>

              </div>

            </div>
          </div>
          <div>
            <div className="card border-primary mb-3 rounded mx-auto" style={{
              maxWidth: '20rem',
              marginLeft: '2rem',
            }}>
              <div className="card-header  text-primary"><i className=" icon bi bi-person-circle"></i><span className="text-capitalize">{user.name ? user.name : "Unregistered"}</span> <Link href="logout"> <i class=" fw-bold float-end bi bi-door-open"></i> </Link> </div>
              <div className="card-body border border-primary">

                <img
                  src="/man.png" height={70} width={70}
                  style={{
                    objectFit: 'cover',
                    borderRadius: "50%",
                    border: "2px solid #593196",
                  }}
                  className=" mx-auto d-block" alt="..."></img>
                <h5 className="card-title text-center mt-2 text-capitalize">{user.name}</h5>
                <div classname=" "
                  style={{
                    marginLeft: '90px',
                    marginBottom: '10px',
                  }}
                >
                  <i className=" icon bi bi-facebook text-primary"></i>
                  <i className=" icon bi bi-twitter text-primary"></i>
                  <i className=" icon bi bi-instagram text-primary"></i>
                </div>
                <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
